function [image_number,p1x,p1y,p2x,p2y,p3x,p3y,p4x,p4y] = importKnownFacesFile()
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [IMAGE_NUMBER,P1X,P1Y,P2X,P2Y,P3X,P3Y,P4X,P4Y] = IMPORTFILE(FILENAME)
%   Reads data from text file FILENAME for the default selection.
%
%   [IMAGE_NUMBER,P1X,P1Y,P2X,P2Y,P3X,P3Y,P4X,P4Y] = IMPORTFILE(FILENAME,
%   STARTROW, ENDROW) Reads data from rows STARTROW through ENDROW of text
%   file FILENAME.
%
% Example:
%   [image_number,p1x,p1y,p2x,p2y,p3x,p3y,p4x,p4y] = importfile();
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2016/05/18 17:47:35

%% Initialize variables.
delimiter = ' ';

startRow = 1;
endRow = inf;


%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen('project_train_data/trainKnownLocations.txt','r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
image_number = dataArray{:, 1};
p1x = dataArray{:, 2};
p1y = dataArray{:, 3};
p2x = dataArray{:, 4};
p2y = dataArray{:, 5};
p3x = dataArray{:, 6};
p3y = dataArray{:, 7};
p4x = dataArray{:, 8};
p4y = dataArray{:, 9};


